application: utamaru001
version: 1
runtime: go
api_version: 2

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /cron/.*
  script: _go_app
  login: admin

- url: /worker/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app

